title: Компьютерные технологии в профессиональной деятельности
email: orlovv@herzen.spb.ru
baseurl: ""
url: ""
github_username:  xunto

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
